version: "3.8"
services:
    mymysql:
        image: "mymysql:latest"
        build: "mymysql"
        restart: unless-stopped
        expose:
        - "3306"
        ports:
        - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: mymysqlroot
            MYSQL_DATABASE: bankanwendung
            MYSQL_USER: Baenker
            MYSQL_PASSWORD: SuperSecure1337
        volumes:
            - ./mymysql/data:/var/lib/mysql
    myredis:
        image: "myredis:latest"
        build: "myredis"
        restart: unless-stopped
        expose:
        - "6379"
        ports:
        - "6379:6379"
        depends_on:
        - mymysql
    bankanwendung:
        image: "bankanwendung:latest"
        build: "bankanwendung"
        restart: unless-stopped
        expose:
        - "8080"
        ports:
        - "8080:8080"
        depends_on:
        - myredis
        - mymysql